spring.application.name=ecommerceapi
spring.sql.init.mode=always
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=[placeholder]
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.separator=;;