apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: default
data:
  datasource-url: jdbc:postgresql://ecommerce-db:5432/ecommerce
  db-name: ecommerce
  spring-profile: "prod"
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  MAX_CONNECTIONS: "10"
