ALTER TABLE orders ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE orders ALTER COLUMN updated_at DROP NOT NULL;
ALTER TABLE order_items ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE order_items ALTER COLUMN updated_at DROP NOT NULL;
ALTER TABLE listings ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE listings ALTER COLUMN updated_at DROP NOT NULL;