ALTER TABLE orders ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE orders ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE order_items ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE order_items ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE listings ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE listings ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;